server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: v1

  ai:
    service:
      url: ${AI_SERVICE_URL:http://python-ai-service:8000}
      chatEndpoint: ${AI_SERVICE_CHAT_ENDPOINT:/eximAI/chat}

    ollama:
      base-url: ${OLLAMA_URL:http://localhost:11434}
      embedding:
        options:
          model: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}

    vectorstore:
      chroma:
        initialize-schema: true
        client:
          host: ${CHROMA_HOST:http://localhost}
          port: ${CHROMA_PORT:8000}

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/exim}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true